identity:    Jeremy Neander
title:       Jeremy Neander
baseurl:     /
url:         https://jneander.com
copyright:   Jeremy Neander 2020
email:       jeremy.neander@gmail.com

description: >
  Jeremy Neander is a software engineer working to build a better, more accessible web.

highlighter: true
markdown:    kramdown

source:      "./jekyll"
destination: "./build"
include:     ["_pages"]
sections:    ["writing", "resume"]

permalink:   "/writing/:title/"
excerpt_separator: ""

plugins:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
